apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: 8978443990/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: database
              value: loizenaidb
            - name: username
              value: postgres
            - name: password
              value: "123"
            - name: host
              value: postgres-service
            - name: dialect
              value: postgres
